version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: thartman/flask_app
    build: ./api
    ports:
      - "4000:4000"
    environment: DB_URL=posrgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  volumes:
    pgdata: {}
